MARIADB_USERNAME = ""
MARIADB_PASSWORD = ""
MARIADB_HOST = ""
MARIADB_PORT = 3309
MARIADB_DATABASE = "r207sms"

MQTT_SERVER = ""
MQTT_PORT = 8883
MQTT_USERNAME = ""
MQTT_PASSWORD = ""
MQTT_TLS_ENABLED = True
MQTT_DISCOVERY_PREFIX = "homeassistant"

ROUTER_ADDRESS = ""
ADMIN_PASSWORD = ""

ROUTER_SSL = True
ROUTER_SSL_ROOT = ""

WIFI_SETTINGS_TO_MQTT = True
